[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install", "npx prisma generate"]

[phases.build]
cmds = ["npm run build", "npx prisma db push --accept-data-loss"]

[start]
cmd = "npm run start"
