[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install", "npx prisma generate"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx prisma db push --accept-data-loss && npm run start"
